
services:

  redis:
    image: redis:7
    ports:
      - 6379:6379

  redis_gui:
    image: redis/redisinsight
    ports:
      - 5540:5540

  maildev:
    image: maildev/maildev
    environment:
      - TZ=Europe/Moscow
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
    ports:
      - '8080:1080'
      - '1025:1025'
    logging:
      driver: 'json-file'
      options:
        max-size: '1m'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus_data/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/datasource.yml:/etc/grafana/provisioning/datasources/datasources.yaml

  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    volumes:
      - ./grafana/loki-config.yml:/etc/loki/local-config.yml